-- ============================================================
-- SAMPLE SEED DATA (bilingual) — QT Drive Innovations
-- Embeddings left NULL until backfill script runs
-- ============================================================

insert into public.knowledge_entries (
  entry_type, obd_code,
  title_en, description_en, likely_causes_en,
  severity_en, recommended_action_en,
  estimated_cost_usd_min, estimated_cost_usd_max,
  title_ja, description_ja, likely_causes_ja,
  severity_ja, recommended_action_ja,
  estimated_cost_jpy_min, estimated_cost_jpy_max,
  embed_text, source
) values
(
  'symptom', null,
  'Grinding noise when braking',
  'A high-pitched or grinding sound occurs when the brake pedal is pressed.',
  array['Worn brake pads', 'Warped rotor', 'Debris stuck in caliper'],
  'Caution - inspect within 1-2 weeks',
  'Visit mechanic for brake inspection',
  150, 400,
  'ブレーキ時にきしむ音がする',
  'ブレーキペダルを踏むと高音またはこすれる音が発生する。',
  array['ブレーキパッドの摩耗', 'ローターの歪み', 'キャリパー内の異物'],
  '注意 - 1〜2週間以内に点検してください',
  'ブレーキ点検のため整備士に相談してください',
  20000, 60000,
  'Grinding noise when braking worn pads warped rotor caliper debris ブレーキ きしむ ゴリゴリ キーキー パッド ローター',
  'seed'
),
(
  'obd_code', 'P0300',
  'Random/Multiple Cylinder Misfire Detected',
  'Engine control module has detected misfires across multiple cylinders.',
  array['Faulty spark plugs', 'Bad ignition coils', 'Fuel injector issues', 'Vacuum leak'],
  'Stop driving - schedule immediate inspection',
  'Do not continue driving; tow or drive minimally to a mechanic',
  100, 800,
  'ランダム/複数シリンダーの失火検出',
  'エンジン制御モジュールが複数のシリンダーで失火を検出しました。',
  array['スパークプラグの不良', 'イグニッションコイルの不良', '燃料インジェクターの問題', '真空漏れ'],
  '直ちに停止 - 即時点検が必要',
  '運転を継続しないでください。整備士まで最小限の運転で移動してください',
  15000, 100000,
  'P0300 random multiple cylinder misfire spark plugs ignition coils fuel injector vacuum ミスファイア 失火 プラグ コイル',
  'seed'
),
(
  'obd_code', 'P0420',
  'Catalyst System Efficiency Below Threshold (Bank 1)',
  'Catalytic converter efficiency may be below threshold on bank 1.',
  array['Failing catalytic converter', 'O2 sensor fault', 'Exhaust leak', 'Upstream misfire'],
  'Caution - inspect soon; may fail emissions',
  'Scan freeze-frame data; check exhaust leaks and O2 sensors before replacing catalyst',
  200, 2500,
  '触媒システム効率低下（バンク1）',
  'バンク1の触媒コンバーター効率が基準を下回っている可能性があります。',
  array['触媒劣化', 'O2センサー不良', '排気漏れ', '上流のミスファイア'],
  '注意 - 早めに点検。排ガス検査に影響する可能性',
  'フリーズフレーム確認。触媒交換前に排気漏れとO2センサーを点検',
  30000, 350000,
  'P0420 catalyst efficiency bank 1 O2 sensor exhaust leak emissions 触媒 排ガス',
  'seed'
),
(
  'symptom', null,
  'Engine overheating with steam',
  'Temperature rises and steam or coolant smell appears from the engine bay.',
  array['Coolant leak', 'Failed thermostat', 'Water pump failure', 'Radiator fan failure'],
  'Stop immediately - risk of severe engine damage',
  'Pull over safely, shut off engine, do not open hot radiator cap; tow if needed',
  100, 1500,
  '蒸気を伴うエンジンオーバーヒート',
  '水温が上昇し、エンジンルームから蒸気やクーラント臭が出る。',
  array['クーラント漏れ', 'サーモスタット不良', 'ウォーターポンプ故障', 'ラジエーターファン故障'],
  '直ちに停止 - 重大なエンジン損傷のリスク',
  '安全に停車しエンジン停止。熱いラジエーターキャップは開けない。必要ならレッカー',
  15000, 200000,
  'engine overheating steam coolant thermostat water pump radiator オーバーヒート 蒸気 クーラント',
  'seed'
),
(
  'symptom', null,
  'Battery no-crank / click only',
  'Starter does not crank; may hear a single click. Lights may be dim.',
  array['Discharged battery', 'Corroded terminals', 'Faulty starter', 'Alternator not charging'],
  'Caution - vehicle may not restart',
  'Test battery CCA and charging voltage; clean terminals',
  50, 600,
  'セルが回らない・カチッという音のみ',
  'スターターが回らず、カチッと音がするだけ。灯火が暗い場合もある。',
  array['バッテリー上がり', '端子腐食', 'スターター不良', 'オルタネーター充電不良'],
  '注意 - 再始動できない可能性',
  'バッテリーCCAと充電電圧を測定。端子を清掃',
  8000, 80000,
  'battery no crank click starter alternator terminals バッテリー セル カチッ',
  'seed'
),
(
  'general_repair', null,
  'Brake pedal sinks to floor',
  'Brake pedal travels unusually far or sinks toward the floor under pressure.',
  array['Brake fluid leak', 'Master cylinder failure', 'Air in brake lines'],
  'Stop immediately - do not continue driving',
  'Stop in a safe place; use hazards; arrange tow. Do not drive.',
  200, 1200,
  'ブレーキペダルが床まで沈む',
  'ブレーキペダルの踏みしろが異常に大きい、または床近くまで沈む。',
  array['ブレーキフルード漏れ', 'マスターシリンダー不良', '配管内エア'],
  '直ちに停止 - 運転を継続しないでください',
  '安全な場所に停車しハザード点灯。レッカーを手配',
  30000, 150000,
  'brake pedal sinks floor hydraulic fluid leak master cylinder ブレーキ ペダル 床 効かない',
  'seed'
),
(
  'symptom', null,
  'AC blows warm air only',
  'Cabin air never gets cold; compressor may not engage or system is low on refrigerant.',
  array['Low refrigerant / leak', 'Failed AC compressor clutch', 'Bad pressure switch', 'Cabin blend door actuator'],
  'Safe to drive - comfort issue',
  'Check for compressor engagement and have system pressure tested for leaks',
  80, 1200,
  'エアコンから冷たい風が出ない',
  '車内が冷えない。コンプレッサーが作動しない、または冷媒不足の可能性。',
  array['冷媒不足・漏れ', 'ACコンプレッサー不良', 'プレッシャースイッチ不良', '内外気/温度ドア不良'],
  '運転可能 - 快適性の問題',
  'コンプレッサー作動を確認し、冷媒圧力と漏れ点検を依頼',
  10000, 150000,
  'AC air conditioning warm air not cold refrigerant compressor clutch エアコン 冷えない クーラー',
  'seed'
),
(
  'symptom', null,
  'Car pulls to one side when braking',
  'Vehicle yaws left or right under braking; may feel vibration in the pedal or steering.',
  array['Uneven pad wear', 'Stuck caliper slide pin', 'Collapsed brake hose', 'Warped rotor one side'],
  'Caution - inspect soon; may reduce stopping performance',
  'Do not delay brake inspection; check pad thickness and caliper free movement',
  120, 500,
  'ブレーキ時に車が片側へ流れる',
  '制動時に左右どちらかへ車が流れる。ペダルやステアに振動が出ることもある。',
  array['パッド片減り', 'キャリパー固着', 'ブレーキホース潰れ', '片側ローター歪み'],
  '注意 - 早めに点検。制動力低下の恐れ',
  'ブレーキ点検を優先。パッド厚とキャリパー作動を確認',
  15000, 70000,
  'pulls to one side braking uneven pads stuck caliper hose rotor ブレーキ 片流れ 片減り',
  'seed'
),
(
  'obd_code', 'P0171',
  'System Too Lean (Bank 1)',
  'ECM reports air-fuel mixture leaner than expected on bank 1.',
  array['Vacuum leak', 'MAF sensor dirty/failing', 'Weak fuel pump or clogged filter', 'O2 sensor fault'],
  'Caution - can cause misfire or catalytic damage if ignored',
  'Smoke-test for vacuum leaks; inspect MAF and fuel pressure before replacing sensors',
  80, 900,
  'システムがリーンすぎる（バンク1）',
  'バンク1の空燃比が基準より薄いとECMが判断している。',
  array['真空漏れ', 'MAFセンサー汚れ・不良', '燃料ポンプ弱い/フィルタ詰まり', 'O2センサー不良'],
  '注意 - 放置すると失火や触媒損傷の恐れ',
  '真空漏れのスモークテスト、MAFと燃圧確認をセンサー交換より先に',
  10000, 120000,
  'P0171 system too lean bank 1 vacuum MAF fuel pump O2 リーン 空燃比 負圧',
  'seed'
),
(
  'symptom', null,
  'Transmission slips or delayed engagement',
  'RPM rises without matching acceleration, or long pause when shifting into Drive/Reverse.',
  array['Low/dirty ATF', 'Worn clutch packs', 'Failing solenoid', 'Torque converter issues'],
  'Caution - risk of stranding; avoid hard acceleration',
  'Check ATF level/condition; scan for transmission codes; limit driving until inspected',
  150, 3500,
  'ミッションが滑る・ギア入りが遅い',
  '回転だけ上がって加速しない、またはD/Rに入れても噛み込みが遅い。',
  array['ATF不足・劣化', 'クラッチ摩耗', 'ソレノイド不良', 'トルコン不良'],
  '注意 - 走行不能のリスク。急加速を避ける',
  'ATF量と状態を確認し、ミッション系コードをスキャン。点検まで控えめに走行',
  20000, 450000,
  'transmission slip delayed engagement ATF solenoid torque converter ミッション 滑る ギア',
  'seed'
);
